connection:
  host: ec2-34-202-88-122.compute-1.amazonaws.com
  username: qtdcvpggpudvxc
  password: f0394ab16fa051e2e5337b571f2d5099a30a648f299cf4dc231c907b7ababbe0
  database: d1vflfg1s4inlb
  sslMode: require
  port: 5432



#spring:
#  security:
#    oauth2:
#      resourceserver:
#        id: https://hackatonpymes.auth0.com/api/v2/
#        jwk:
#          jwk-set-uri: https://hackatonpymes.auth0.com/.well-known/jwks.json
#          issuer-uri: https://hackatonpymes.auth0.com/
