connection:
  host: ec2-18-210-214-86.compute-1.amazonaws.com
  username: kkascofhdryqkd
  password: c5b90f174e0c69f1146da3a88dd5fa8859c1f2ef541e9c523031e3c78ddf79d9
  database: daknfqg9qlcnb6
  sslMode: require
  port: 5432



#spring:
#  security:
#    oauth2:
#      resourceserver:
#        id: https://hackatonpymes.auth0.com/api/v2/
#        jwk:
#          jwk-set-uri: https://hackatonpymes.auth0.com/.well-known/jwks.json
#          issuer-uri: https://hackatonpymes.auth0.com/
